version: '3'
services:
  redis-server:
    image: 'redis'
    container_name: redis-server
    ports:
      - "6379:6379"
  app:
    image: server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - redis-server
